language: python
python:
  - "2.7"
  - "3.4"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - "pip install flake8"
  - "pip install -e .[dev]"
before_script:
  - flake8 planet tests
script:
  - "py.test tests"
