DOCKER_EXE:=$(if $(strip $(DOCKER_EXE)),$(DOCKER_EXE),docker)
DOCKER_NAME:=$(if $(strip $(DOCKER_NAME)),$(strip $(DOCKER_NAME)),$(strip $(PROJ_NAME)))
DOCKER_REGISTRY:=$(if $(strip $(DOCKER_REGISTRY)),$(strip $(DOCKER_REGISTRY)),__DOCKER_REGISTRY_unset__)

DOCKER_FQNAME=$(DOCKER_REGISTRY)/$(DOCKER_NAME)

# Don't let branches clobber tags from master!
ifeq ($(GIT_BRANCH_SLUG),master)
	DOCKER_TAG_BRANCH_SLUG=
else
	DOCKER_TAG_BRANCH_SLUG=-$(GIT_BRANCH_SLUG)
endif

# Local developer builds get docker tags that ID them as such, to minimize
# colissions with official CI/CD builds.
DOCKER_DEVELOPMENT_DECORATOR=$(if $(CI_COMMIT_SHA),,--development--$(USER_NAME))

DOCKER_TAG_VERSION=$(VERSION)$(DOCKER_TAG_BRANCH_SLUG)$(DOCKER_DEVELOPMENT_DECORATOR)
DOCKER_TAG_VERSION_AND_SHA=$(VERSION)$(DOCKER_TAG_BRANCH_SLUG)-$(GIT_SHA)$(DOCKER_DEVELOPMENT_DECORATOR)
DOCKER_TAG_VERSION_AND_BUILD=$(VERSION).$(BUILD_NUM)$(DOCKER_TAG_BRANCH_SLUG)$(DOCKER_DEVELOPMENT_DECORATOR)
DOCKER_TAG_VERSION_AND_BUILD_AND_SHA=$(VERSION).$(BUILD_NUM)$(DOCKER_TAG_BRANCH_SLUG)-$(GIT_SHA)$(DOCKER_DEVELOPMENT_DECORATOR)

